### ISSUE TITLE
Update templates to support namespace install

### ISSUE THREAD

**Issue by da-ar** [puppetlabs/baker-round#21]
`pct install` now places templates in a namespaced directory structure: `author/id/version`.

baker-round is a temporary location for  our default templates and is simply cloned to the correct location for installation. In order for this to work with the new directory structure, backer-round must be changed to include the correct directory structure.

This will not be an issue for community templates as they will be installed by PCT. Community templates must also reside in a single repo.

**Comment by michaeltlombardi** [comment]
Resolved by #22
